language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cico643/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cico643/docker-react npm run test